apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-tier
spec:
  replicas: 1
  template:
    metadata:
      name: data-tier
      labels:
        app: demo
        tier: data
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              protocol: TCP


