apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: support-tier
spec:
  replicas: 20
  template:
    metadata:
      name: support-tier
      labels:
        support: demo
        tier: support
    spec:
      containers:
        - name: counter
          image: slashdeploy/microservice-example:counter-v1
          env:
            - name: API_URL
              value: "http://$(APP_TIER_SERVICE_HOST):$(APP_TIER_SERVICE_PORT_SERVER)"

        - name: poller
          image: slashdeploy/microservice-example:poller-v1
          env:
            - name: API_URL
              value: "http://$(APP_TIER_SERVICE_HOST):$(APP_TIER_SERVICE_PORT_SERVER)"
